### ISSUE TITLE
意外崩溃和闪退

### ISSUE THREAD

**Issue by 594hjd** [Theresa-0328/MHY_Scanner#100]
![QQ截图20240915124436](https://github.com/user-attachments/assets/3962bf8f-4f82-4c94-8665-d03cdb0d6084)

**Comment by Theresa-0328** [comment]
上传你的dump文件，默认保存在当前目录

**Comment by 594hjd** [comment]
[MHY_Scanner-20240912-193124.dmp](https://github.com/user-attachments/files/17040659/MHY_Scanner-20240912-193124.dmp)
[MHY_Scanner-20240915-124251.dmp](https://github.com/user-attachments/files/17040661/MHY_Scanner-20240915-124251.dmp)
[MHY_Scanner-20240915-124417.dmp](https://github.com/user-attachments/files/17040662/MHY_Scanner-20240915-124417.dmp)
[MHY_Scanner-20240915-124556.dmp](https://github.com/user-attachments/files/17040663/MHY_Scanner-20240915-124556.dmp)
[MHY_Scanner-20240915-124646.dmp](https://github.com/user-attachments/files/17040664/MHY_Scanner-20240915-124646.dmp)

**Comment by Theresa-0328** [comment]
和 #81 类似，访问某些接口后返回了空。在获取B站直播链接时和验证stoken时都返回了空，你可以更换网络环境再尝试。后续会对curl进行版本升级和重新封装，可能没有考虑到某些特殊情况。另外这几个dump文件都是监视直播间时的崩溃，监视屏幕时有相同的问题吗？

**Comment by 594hjd** [comment]
监视屏幕时并未出现过相同的问题，只在监视直播间时存在崩溃
