### ISSUE TITLE
不明崩溃问题

### ISSUE THREAD

**Issue by zm1727986495** [Theresa-0328/MHY_Scanner#102]
dump文件在哪

**Comment by Theresa-0328** [comment]
默认位置在程序的运行目录

**Comment by zm1727986495** [comment]
![image](https://github.com/user-attachments/assets/be6c80c6-106b-42e6-9a5d-cf6e096f3dd9)

**Comment by zm1727986495** [comment]
是因为显卡的问题吗

**Comment by Theresa-0328** [comment]
我没有使用NVIDIA显卡专有特性，但我没有在amd显卡上测试过，可能存在适配性问题。上传你的dump文件，我没有看到你的dump前不能确定。

**Comment by zm1727986495** [comment]
![image](https://github.com/user-attachments/assets/59a6daa0-8909-42ef-81ea-b35609a2159a)
我这里面好像没有dump文件

**Comment by zm1727986495** [comment]
我这里面好像没有dump文件
![Uploading image.png…]()

**Comment by zm1727986495** [comment]
我这里面好像没有dump文件
![image](https://github.com/user-attachments/assets/66fd9858-4302-4acd-ae32-9cf434bd3787)

**Comment by Theresa-0328** [comment]
新版本即将发布，新版本如果还有问题再处理了
