### ISSUE TITLE
请教一下从直播流抢码的实现思路

### ISSUE THREAD

**Issue by itdengwenbin** [Theresa-0328/MHY_Scanner#12]
大佬可以讲下从直播流获取二维码登录是怎么实现的吗，我试试解析抖音直播间。
（我学的Python没学过C++，看本项目的源码没看懂[尴尬]）

**Comment by Theresa-0328** [comment]
抖音直播流地址现在应该是需要cookie才可以获取，而且改动频繁，我对前端也不太了解，需要参考别的项目的实现，做起来有点麻烦。如果你获取到了流地址，就可以进行拉流和解码为帧，再解析二维码就可以了，然后尽可能的快。

**Comment by itdengwenbin** [comment]
> 抖音直播流地址现在应该是需要cookie才可以获取，而且改动频繁，我对前端也不太了解，需要参考别的项目的实现，做起来有点麻烦。如果你获取到了流地址，就可以进行拉流和解码为帧，再解析二维码就可以了，然后尽可能的快。

拉流和解码用什么技术（或第三方库）实现？

**Comment by Theresa-0328** [comment]
我使用的是curl和ffmpeg。

**Comment by itdengwenbin** [comment]
> 我使用的是curl和ffmpeg。

好的，我研究研究

**Comment by itdengwenbin** [comment]
抖音直播流地址可以油猴脚本拿到
`// ==UserScript==
// @name         抖音直播解析
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://live.douyin.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=douyin.com
// @grant        none
// @require      https://unpkg.com/sweetalert2@11.4.17/dist/sweetalert2.all.min.js
// ==/UserScript==

window.onload = function () {
    function send_toast(icon, title, text, time, pos) { // 将提示封装成函数以便调用
        const Toast = Swal.mixin({
            toast: true,
            position: pos,
            showConfirmButton: false,
            timer: time,
            text: text,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            },
        });
        Toast.fire({
            icon: icon,
            title: title,
        })
    }
    let flv=JSON.parse(JSON.parse(decodeURIComponent(window.document.getElementById("RENDER_DATA").innerText)).app.initialState.roomStore.roomInfo.room.stream_url.live_core_sdk_data.pull_data.stream_data).data.origin.main.flv
    send_toast('success', '解析到FLV地址', flv, 10000, 'top')

}`
这个脚本在浏览器进入抖音直播间后自动解析原画的flv链接
![image](https://github.com/Theresa-0328/MHY_Scanner/assets/52495231/5d98c84b-bf7e-4e94-b293-da6b7fe4dc78)

**Comment by Theresa-0328** [comment]
了解了，可能会考虑添加。
