### ISSUE TITLE
第二天的时候经常会出现，扫码失败

### ISSUE THREAD

**Issue by kongbai312** [Theresa-0328/MHY_Scanner#15]
百度了一下米游社的token应该能存在好长一段时间，应该不会是验证失效问题吧，直播流获取数据扫码还没有通过插件取消直播缓存手动扫码来的快。问一下大佬会是啥原因？按理来说通过直播数据流从代码中识别二维码并登录应该是最快的呀

**Comment by Theresa-0328** [comment]
每次扫码前都有token失效检测，失效会进行提示，你的问题与token无关。建议关闭代理软件再试，每个人的设备和网络环境都有很大不同，没有接到更多报告前只能暂时认为是你个人环境问题。另外我不太明白你说的第二天是什么意思，是指第一天一切正常吗？最后，你可以提供一下你抢的直播间号和尝试次数。

**Comment by kongbai312** [comment]
> 每次扫码前都有token失效检测，失效会进行提示，你的问题与token无关。建议关闭代理软件再试，每个人的设备和网络环境都有很大不同，没有接到更多报告前只能暂时认为是你个人环境问题。另外我不太明白你说的第二天是什么意思，是指第一天一切正常吗？最后，你可以提供一下你抢的直播间号和尝试次数。

对的第一天正常，第二天的时候就抢不上了，总比别人慢一步，那我试试代理关了，重新启动尝试一下，直播间我是B站随便找的。

**Comment by shenhuaaoding** [comment]
请问为何我获取到的ck粘贴上去说我格式错误呢。我觉得我获取的ck应该没问题呀
