### ISSUE TITLE
可以增加一个延时登录的功能吗

### ISSUE THREAD

**Issue by Mr-Deng67** [Theresa-0328/MHY_Scanner#17]
因为码一被扫就立马登进去了，很容易让主播怀疑用挂。可以加一个输入框，支持输入一个浮点数表示延时多少秒。抢码成功后让线程睡眠这么多秒后再发送确认登录请求。

**Comment by Theresa-0328** [comment]
必要性不是特别高，选择权是否需要给用户也在考虑。

**Comment by itdengwenbin** [comment]
> 必要性不是特别高，选择权是否需要给用户也在考虑。

嗯，用户手动确认登录也可以

**Comment by shenhuaaoding** [comment]
> > 必要性不是特别高，选择权是否需要给用户也在考虑。
> 
> 嗯，用户手动确认登录也可以

请问您是如何获取ck的呢。我按照网传的f12开发者模式获取的ck显示格式错误。

**Comment by itdengwenbin** [comment]
> > > 必要性不是特别高，选择权是否需要给用户也在考虑。
> > 
> > 
> > 嗯，用户手动确认登录也可以
> 
> 请问您是如何获取ck的呢。我按照网传的f12开发者模式获取的ck显示格式错误。
按F12点控制台，输入`document.cookie`回车，鼠标放到返回的结果上右键 -> 复制字符串

**Comment by shenhuaaoding** [comment]
> > > > 必要性不是特别高，选择权是否需要给用户也在考虑。
> > > 
> > > 
> > > 嗯，用户手动确认登录也可以
> > 
> > 
> > 请问您是如何获取ck的呢。我按照网传的f12开发者模式获取的ck显示格式错误。
> 
> 按F12点控制台，输入回车，鼠标放到返回的结果上右键 -> 复制字符串`document.cookie`
抱歉，我还是不了解。可否具体一点呢，感谢

**Comment by shenhuaaoding** [comment]
> > > > 必要性不是特别高，选择权是否需要给用户也在考虑。
> > > 
> > > 
> > > 嗯，用户手动确认登录也可以
> > 
> > 
> > 请问您是如何获取ck的呢。我按照网传的f12开发者模式获取的ck显示格式错误。
> 
> 按F12点控制台，输入`document.cookie`回车，鼠标放到返回的结果上右键 -> 复制字符串

感谢您的方式，但是我使用此方式获取的ck仍然显示ck格式错误。不知为何

**Comment by shenhuaaoding** [comment]
> > > > 必要性不是特别高，选择权是否需要给用户也在考虑。
> > > 
> > > 
> > > 嗯，用户手动确认登录也可以
> > 
> > 
> > 请问您是如何获取ck的呢。我按照网传的f12开发者模式获取的ck显示格式错误。
> 
> 按F12点控制台，输入`document.cookie`回车，鼠标放到返回的结果上右键 -> 复制字符串

感谢您的方式
