### ISSUE TITLE
备注有时候会自动还原

### ISSUE THREAD

**Issue by linzhibinghan** [Theresa-0328/MHY_Scanner#30]
改完了备注,然后下次开机运行,发现会自动还原成1 2 3 4 5 6之类的..
![QQ截图20231120155341](https://github.com/Theresa-0328/MHY_Scanner/assets/12961467/816aacbb-7c02-4427-bbb1-e81e8ce7312f)

**Comment by linzhibinghan** [comment]
> 版本是1.1.5最新版吗？

是的,不过我重新设置了一下好像又没问题了...我之前直接拿1.1.5覆盖的,后来不放心又全删,重新解压了一遍,可能中间有操作影响到了...我先多测几天看看..打扰了..

**Comment by Theresa-0328** [comment]
1.1.4 有这个问题，可能没有修好

**Comment by linzhibinghan** [comment]
> 1.1.4 有这个问题，可能没有修好

这几天好像没出现过这个问题了,应该没事.

**Comment by linzhibinghan** [comment]
> 1.1.4 有这个问题，可能没有修好

又还原了,可能是强制关机丢数据的关系...我开着游戏挂机弄了一个自动关机..

**Comment by linzhibinghan** [comment]
> 1.1.4 有这个问题，可能没有修好

还有一个发现就是最近日常多开改用云原神了,好像不能支持云原神的扫码
