### ISSUE TITLE
1.1.5版本使用监视屏幕导致程序闪退

### ISSUE THREAD

**Issue by Yoimiya-993** [Theresa-0328/MHY_Scanner#31]
1.1.5版本的监视屏幕功能好像用不了，每次点监视屏幕过几秒程序就闪退了

**Comment by Theresa-0328** [comment]
你的设备的显卡是什么? 你可以检查下是否正常安装了DirectX12，参考[微软官方的链接](https://support.microsoft.com/zh-cn/topic/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC%E7%9A%84-directx-d1f5ffa5-dae2-246c-91b1-ee1e973ed8c2)

**Comment by Yoimiya-993** [comment]
我找到问题了，NVIDIA控制面板这里之前改成了“高性能NVIDIA处理器”，现在改回“自动选择”监视屏幕就可以用了
![image](https://github.com/Theresa-0328/MHY_Scanner/assets/52495231/15302420-f067-4ef5-b287-d28fa7fcfc7e)

**Comment by Theresa-0328** [comment]
我手上没有使用核显的设备导致没有注意到这一问题，下版本将尝试修复。

**Comment by BiFangKNT** [comment]
> 我手上没有使用核显的设备导致没有注意到这一问题，下版本将尝试修复。

请问修复了吗？我这里依旧频繁闪退。显卡是3060，开启了独显直连。系统是Windows 11 专业版 23H2 22631.2715。

**Comment by BiFangKNT** [comment]
> 我手上没有使用核显的设备导致没有注意到这一问题，下版本将尝试修复。

补充一下，显卡是3060 laptop

**Comment by Yoimiya-993** [comment]
> > > > 我手上没有使用核显的设备导致没有注意到这一问题，下版本将尝试修复。
> > > 
> > > 
> > > 请问修复了吗？我这里依旧频繁闪退。显卡是3060，开启了独显直连。系统是Windows 11 专业版 23H2 22631.2715。
> > 
> > 
> > 应该是用不了独显，我把显卡改成自动选择后，打开任务管理器发现调用的是核显
> 
> 可是我想开独显直连玩崩三啊，独显直连下屏蔽核显的。其实倒也不是每次都闪退，偶尔可以扫成功，只是成功率很低。

NVIDIA控制面板里可以调的，它不是有全局设置和程序设置，全局用自动选择，程序里选择崩坏3给它调成独显

**Comment by BiFangKNT** [comment]
> > > > > 我手上没有使用核显的设备导致没有注意到这一问题，下版本将尝试修复。
> > > > 
> > > > 
> > > > 请问修复了吗？我这里依旧频繁闪退。显卡是3060，开启了独显直连。系统是Windows 11 专业版 23H2 22631.2715。
> > > 
> > > 
> > > 应该是用不了独显，我把显卡改成自动选择后，打开任务管理器发现调用的是核显
> > 
> > 
> > 可是我想开独显直连玩崩三啊，独显直连下屏蔽核显的。其实倒也不是每次都闪退，偶尔可以扫成功，只是成功率很低。
> 
> NVIDIA控制面板里可以调的，它不是有全局设置和程序设置，全局用自动选择，程序里选择崩坏3给它调成独显

调不了的，独显直连直接从硬件上屏蔽了核显，控制面板直接识别不到核显的

**Comment by BiFangKNT** [comment]
> 在尝试解决，主要我没有类似的设备不太好测试

你没有支持独显直连的笔记本或者使用不带核显的cpu（比如5600x）的台式机吗

**Comment by Theresa-0328** [comment]
> > 在尝试解决，主要我没有类似的设备不太好测试
> 
> 你没有支持独显直连的笔记本或者使用不带核显的cpu（比如5600x）的台式机吗

我的设备是不带核显的2070笔记本和不带核显的台式，没有需要手动选择显卡的场景，如果用不了就先回退到1.1.4版本吧

**Comment by BiFangKNT** [comment]
> > > 在尝试解决，主要我没有类似的设备不太好测试
> > 
> > 
> > 你没有支持独显直连的笔记本或者使用不带核显的cpu（比如5600x）的台式机吗
> 
> 我的设备是不带核显的2070笔记本和不带核显的台式，没有需要手动选择显卡的场景，如果用不了就先回退到1.1.4版本吧

不是，我从1.1.2版本开始使用的，那个时候就是这样频繁闪退了。另外独显直连下就相当于系统里没有核显了，因为从硬件上屏蔽了核显了。

**Comment by BiFangKNT** [comment]
> > > 在尝试解决，主要我没有类似的设备不太好测试
> > 
> > 
> > 你没有支持独显直连的笔记本或者使用不带核显的cpu（比如5600x）的台式机吗
> 
> 我的设备是不带核显的2070笔记本和不带核显的台式，没有需要手动选择显卡的场景，如果用不了就先回退到1.1.4版本吧

会不会是win11的问题？

**Comment by BiFangKNT** [comment]
> > > 在尝试解决，主要我没有类似的设备不太好测试
> > 
> > 
> > 你没有支持独显直连的笔记本或者使用不带核显的cpu（比如5600x）的台式机吗
> 
> 我的设备是不带核显的2070笔记本和不带核显的台式，没有需要手动选择显卡的场景，如果用不了就先回退到1.1.4版本吧

我似乎找到了规律。我的崩三是全屏启动的，当我在其他页面（比如说在浏览器最大化显示的页面）启动扫码器，再切到崩三的页面时，扫码器就几乎每次都会闪退；而当我在崩三的页面按win键呼出菜单，直接在“开始”屏幕启动扫码器的话，扫码器就没有闪退了。
