### ISSUE TITLE
损坏的映像

### ISSUE THREAD

**Issue by yukiryo** [Theresa-0328/MHY_Scanner#35]
![image](https://github.com/Theresa-0328/MHY_Scanner/assets/58250223/05f1b116-68c0-496a-bc2b-1969721e51c3)
![image](https://github.com/Theresa-0328/MHY_Scanner/assets/58250223/d8aad4f3-dd1a-47ea-9c5d-e7f826635133)

**Comment by Theresa-0328** [comment]
检查有没有正确安装最新的vc runtime (Visual Studio 2015、2017、2019 和 2022)，[微软官方的解释及下载链接](https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170)
