### ISSUE TITLE
access_key会导致无法打开软件闪退

### ISSUE THREAD

**Issue by a776058959** [Theresa-0328/MHY_Scanner#37]
就是我有大概快一个月没用这软件了，然后今天手机不在身边，想着在电脑上打个乐土。
然后发现打开是白的
![图片](https://github.com/Theresa-0328/MHY_Scanner/assets/58454818/5df610cc-3c50-4b60-83fc-24ab6a39f27c)
，然后过一会软件窗口就没了。
我不知道咋回事就下载了最新的，结果还是不行，一样的问题。
然后看到其他人提的开启监视屏幕后闪退，就寻思是不是同样的问题，就去配置文件里把true全改成了false，结果还是不行，我就直接把配置文件改了个名，软件就能打开了，然后登上账号之后对比了新的配置文件，也没区别啊，唯一的区别就是access_key，我就把原来的配置文件的access_key改成了新的，结果也没事了，所以我觉得应该是这玩意过期了导致软件打不开的？我试了试改了新的access_key里边的一个字母，然后就出现同样问题了，所以能确定是access_key的锅。

**Comment by Theresa-0328** [comment]
了解问题了，是b服还是官服？

**Comment by a776058959** [comment]
> 了解问题了，是b服还是官服？

B服
