### ISSUE TITLE
启动程序的时候无法定位程序输入点_std_tzdb_delete_current zone于动态链接库D:\桌面\MHY_Scanner_v1.1.5MHY_Scanner.exe 上.

### ISSUE THREAD

**Issue by z12349** [Theresa-0328/MHY_Scanner#47]

**Comment by 594hjd** [comment]
同样的问题

**Comment by Theresa-0328** [comment]
此类问题是没有安装vc runtime2022。[微软的官方下载链接](https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by 594hjd** [comment]
> 此类问题是没有安装vc runtime2022。[微软的官方下载链接](https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170)

已解决，感谢

**Comment by z12349** [comment]
我用dll修复工具弄好了，谢谢
