### ISSUE TITLE
弹窗置顶后没有获得焦点

### ISSUE THREAD

**Issue by Yoimiya-993** [Theresa-0328/MHY_Scanner#61]
之前没有窗口置顶的时候，切回软件窗口可以直接回车把二次确认登录，登录成功等这些弹窗的确认点掉。现在窗口自动置顶发现不行了，是不是失去焦点的原因

**Comment by Theresa-0328** [comment]
[MHY_Scanner.zip](https://github.com/Theresa-0328/MHY_Scanner/files/14759063/MHY_Scanner.zip)

你可以尝试一下这个版本，替换掉安装文件夹里原本的MHY_Scanner.exe，观察问题是否仍然存在

**Comment by Yoimiya-993** [comment]
没有问题了，有个小瑕疵：登录成功后按钮的文本没改回去
![image](https://github.com/Theresa-0328/MHY_Scanner/assets/52495231/67dea4dd-d696-4cb2-804f-42281bb420f6)
