### ISSUE TITLE
无法添加账号，一添加账号就会卡住然后闪退

### ISSUE THREAD

**Issue by oouuuyyyy** [Theresa-0328/MHY_Scanner#62]

**Comment by Theresa-0328** [comment]
需要更多信息

**Comment by oouuuyyyy** [comment]
[QQ录屏.zip](https://github.com/Theresa-0328/MHY_Scanner/files/14759394/QQ.zip)

**Comment by shenhuaaoding** [comment]
> 需要更多信息

您好，此版本我也遇见了这个问题，将ck复制到框内，点击登陆就会卡住闪退

**Comment by rxc888** [comment]
我也是，添加完cookie后程序就闪退了

**Comment by Theresa-0328** [comment]
cookie已失效，cookie相关问题不会处理了
