### ISSUE TITLE
一直提示cookie格式错误

### ISSUE THREAD

**Issue by Reminisceee** [Theresa-0328/MHY_Scanner#63]
一直提示cookie格式错误，我想知道cookie格式到底什么样啊

**Comment by shenhuaaoding** [comment]
有多种办法，可以上哔哩哔哩查看视频教程

**Comment by Reminisceee** [comment]
我知道怎么获得cookie，这个添加账号的cookie格式是什么。
我用谷歌浏览器得到的cookie是这种格式：_MHYUUID=xxxx; _MHYUUID=xxxx; DEVICEFP_SEED_ID=xxxx; DEVICEFP_SEED_TIME=xxxx; DEVICEFP=xxxx; _ga=xxxx; MIHOYO_LOGIN_PLATFORM_LIFECYCLE_ID=xxxx; cookie_token_v2=xxxx; ltoken=xxxx; ltuid=xxxx; _ga_KS4J8TXSHQ=xxxx

**Comment by shenhuaaoding** [comment]
> 我知道怎么获得cookie，这个添加账号的cookie格式是什么。 我用谷歌浏览器得到的cookie是这种格式：_MHYUUID=xxxx;_MHYUUID=xxxx;DEVICEFP_SEED_ID=xxxx;DEVICEFP_SEED_TIME=xxxx;DEVICEFP=xxxx;_ga=xxxx;MIHOYO_LOGIN_PLATFORM_LIFECYCLE_ID=xxxx;cookie_token_v2=xxxx;ltoken=xxxx;ltuid=xxxx;_ga_KS4J8TXSHQ=xxxx

添加账号并没有要求ck格式，只需复制粘贴就行。你显示格式错误，是因为ck获取不对，你获取的压根不是ck。而不是格式问题。

**Comment by Reminisceee** [comment]
![image](https://github.com/Theresa-0328/MHY_Scanner/assets/94025721/0ef71152-9dc8-4356-8a03-650213f4cda4)
这不是ck？

**Comment by Reminisceee** [comment]
![image](https://github.com/Theresa-0328/MHY_Scanner/assets/94025721/3d7a234e-073b-44b9-ac3c-619e361dd7f2)
这不是ck？

**Comment by shenhuaaoding** [comment]
> ![image](https://private-user-images.githubusercontent.com/94025721/317152047-3d7a234e-073b-44b9-ac3c-619e361dd7f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjA2ODgsIm5iZiI6MTcxMTUyMDM4OCwicGF0aCI6Ii85NDAyNTcyMS8zMTcxNTIwNDctM2Q3YTIzNGUtMDczYi00NGI5LWFjM2MtNjE5ZTM2MWRkN2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA2MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MDhkMjZhN2UwY2YwOTU2ODhmMjlkOGI3N2VkYWM5YTJjZDVjYjY0NDZhNjE4Mzk1ZDUxMmVlY2NlMWM5NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FKBSqTIVAoXsaGLAD63YXg3uQDDOq44tdz57I0JmN24)这不是ck？

![W8KLQJ5~A4MS@O`J@3MZCE9](https://github.com/Theresa-0328/MHY_Scanner/assets/131860715/3290023a-9a63-481e-bd2b-5e56733ba624)

**Comment by Reminisceee** [comment]
我现在懂了，是米游社的cookie，不能是原神的cookie

**Comment by Reminisceee** [comment]
可以了，只能用在米游社账号管理界面获得的ck，其他界面不行

**Comment by shenhuaaoding** [comment]
> 可以了，只能用在米游社账号管理界面获得的ck，其他界面不行

请问你输入ck之后，点击登陆会出现闪退问题吗

**Comment by Reminisceee** [comment]
这不还是有格式要求吗？
uni_web_token=; cookie_token=xxx; account_id=xxx; ltoken=xxx; ltuid=xxx; cookie_token_v2=xxx; account_mid_v2=xxx; account_id_v2=xxx; ltoken_v2=xxx.CAE=; ltmid_v2=xxx; ltuid_v2=xxx; _MHYUUID=xxx; DEVICEFP_SEED_ID=xxx; DEVICEFP_SEED_TIME=xxx; DEVICEFP=xxx; login_uid=160719262; login_ticket=xxx 
这些信息在其他界面也可以获得，只支持这种格式的

**Comment by Reminisceee** [comment]
> > 可以了，只能用在米游社账号管理界面获得的ck，其他界面不行
> 
> 请问你输入ck之后，点击登陆会出现闪退问题吗

没有，可以导入

**Comment by shenhuaaoding** [comment]
> > > 可以了，只能用在米游社账号管理界面获得的ck，其他界面不行
> > 
> > 
> > 请问你输入ck之后，点击登陆会出现闪退问题吗
> 
> 没有，可以导入

那请问你点击监视屏幕会出现闪退吗

**Comment by Reminisceee** [comment]
没有闪退，可以正常扫码

**Comment by Reminisceee** [comment]
再添加一些诸如可以自定义选取区域，连续扫码的功能就更好了

**Comment by Yoimiya-993** [comment]
> > > > 可以了，只能用在米游社账号管理界面获得的ck，其他界面不行
> > > 
> > > 
> > > 请问你输入ck之后，点击登陆会出现闪退问题吗
> > 
> > 
> > 没有，可以导入
> 
> 那请问你点击监视屏幕会出现闪退吗

我在手机上用向日葵远控电脑监视屏幕会闪退

**Comment by Reminisceee** [comment]
> > > > > 可以了，只能用在米游社账号管理界面获得的ck，其他界面不行
> > > > 
> > > > 
> > > > 请问你输入ck之后，点击登陆会出现闪退问题吗
> > > 
> > > 
> > > 没有，可以导入
> > 
> > 
> > 那请问你点击监视屏幕会出现闪退吗
> 
> 我在手机上用向日葵远控电脑监视屏幕会闪退

没有闪退，可以正常扫码登录游戏
