### ISSUE TITLE
一直显示登录状态失效

### ISSUE THREAD

**Issue by Xin-arwanas** [Theresa-0328/MHY_Scanner#70]
![C{2}NB2OMRJ{_ N PVE_~2R](https://github.com/Theresa-0328/MHY_Scanner/assets/42599693/62c550f4-382b-40fa-8c31-6eb4cd53d70c)
重新去获取一下cookie也显示登录状态失效

**Comment by wang4386** [comment]
我也是这样的，而且旧版本都打不开了

**Comment by 1714775263** [comment]
暂时没办法 好像接口返回结果被关闭了

**Comment by Xin-arwanas** [comment]
我发现了，两台设备一台可以一台不行，第一次用的那个可以

**Comment by 1714775263** [comment]
> 我发现了，两台设备一台可以一台不行，第一次用的那个可以

什么原理

**Comment by Xin-arwanas** [comment]
> > 我发现了，两台设备一台可以一台不行，第一次用的那个可以
> 
> 什么原理

我也不太清楚

**Comment by Xin-arwanas** [comment]
> > 我发现了，两台设备一台可以一台不行，第一次用的那个可以
> 
> 什么原理

原来是我第一台设备还保留着以前的token，新获取的就不行了

**Comment by ghostorange1** [comment]
我是之前用过别的获取过cookie，然后旧的删除不了这个记录，现在是同样的问题，想问一下有解决方法吗

**Comment by Xin-arwanas** [comment]
> 我是之前用过别的获取过cookie，然后旧的删除不了这个记录，现在是同样的问题，想问一下有解决方法吗

目前只有他改之前的cookie能用，这个方法新获取的都用不了了

**Comment by vdbrcxby** [comment]
https://github.com/vdbrcxby/YS-SCANNER，可以看看这个支持添加账号，小窗模式,等诸多功能

**Comment by yebai137** [comment]
+1+1 也是这个问题 @Theresa-0328 ~
