### ISSUE TITLE
已添加新账号，但是弹窗无法识别

### ISSUE THREAD

**Issue by soullzm** [Theresa-0328/MHY_Scanner#71]
![图片反馈](https://github.com/Theresa-0328/MHY_Scanner/assets/126051470/39cec22d-86b4-4ace-b658-a6af0ad13b2a)

![图片反馈03](https://github.com/Theresa-0328/MHY_Scanner/assets/126051470/385e5093-c7d3-4329-99ca-7a98b13c9bf7)

如图所示，按照以前提取COOKIE的办法添加账号后，显示“登录状态失效”

**Comment by danaokuoao** [comment]
好像现在都是这样了，除非以前就添加了账号

**Comment by soullzm** [comment]
> 好像现在都是这样了，除非以前就添加了账号

是的，以前的还是可以继续抢码

**Comment by 594hjd** [comment]
最近账号更新了一下，重新获取的和之前的cookie都无法正常扫码登录了。
