### ISSUE TITLE
重新获取ck还是这种状况

### ISSUE THREAD

**Issue by hanserliave** [Theresa-0328/MHY_Scanner#75]
![`POO E{X8F}W5TWL9WU~2MK](https://github.com/Theresa-0328/MHY_Scanner/assets/168754629/fa5187cb-2f67-4643-92d6-948ae149b278)
直接就是扫不了了

**Comment by keaiye** [comment]
看commit应该修复了，但还没编译发布到Releases

**Comment by CanDuanQi** [comment]
我看作者更新了代码 但是没有更新release 小白不会跑 也很着急哈哈哈

**Comment by Theresa-0328** [comment]
目前仍有导致不可用bug未解决

**Comment by rxc888** [comment]
我也有这问题了

**Comment by whaleyu818** [comment]
同样有这种问题呜呜呜...
什么时候能解决呢，在线等...
