### ISSUE TITLE
屏幕监控和直播间都没反应

### ISSUE THREAD

**Issue by kuronekoda** [Theresa-0328/MHY_Scanner#8]
![image](https://github.com/Theresa-0328/MHY_Scanner/assets/136661812/787e48f5-68e9-4a8d-b3ff-a82f32d0e8e1)

**Comment by Theresa-0328** [comment]
当前版本没有添加对原神的支持，可能在接下来几个版本添加

**Comment by kuronekoda** [comment]
> 
刚刚试了下星穹铁道可以扫码登录，希望作者增加一下原神扫码，十分感谢！
