### ISSUE TITLE
添加账号后没有反应，卡住

### ISSUE THREAD

**Issue by oouuuyyyy** [Theresa-0328/MHY_Scanner#81]
[MHY_Scanner-20240625-143904.dmp](https://github.com/user-attachments/files/15966055/MHY_Scanner-20240625-143904.dmp)

**Comment by Theresa-0328** [comment]
检查这个链接是否可以正常访问https://bbs-api.miyoushe.com/user/api/getUserFullInfo?uid=1 dump文件显示你访问这个接口时返回了空

**Comment by oouuuyyyy** [comment]
![20240625203646](https://github.com/Theresa-0328/MHY_Scanner/assets/127332016/fe6de7bc-9151-427e-aae3-44ee77f25e71)
显示是这样的

**Comment by oouuuyyyy** [comment]
{
    "data": null,
    "message": "user not exist",
    "retcode": -20001
}

**Comment by Theresa-0328** [comment]
把链接最后的uid换位你自己米游社的uid，26076开头的这个测试一下

**Comment by oouuuyyyy** [comment]
{
    "retcode": 0,
    "message": "OK",
    "data": {
        "user_info": {
            "uid": "260769475",
            "nickname": "现在就能赢",
            "introduce": "就这样吧",
            "avatar": "100560",
            "gender": 0,
            "certification": {
                "type": 0,
                "label": ""
            },
            "level_exps": [
                {
                    "level": 6,
                    "exp": 3944,
                    "game_id": 2
                },
                {
                    "level": 3,
                    "exp": 426,
                    "game_id": 6
                },
                {
                    "level": 4,
                    "exp": 727,
                    "game_id": 5
                },
                {
                    "level": 3,
                    "exp": 265,
                    "game_id": 1
                },
                {
                    "level": 4,
                    "exp": 875,
                    "game_id": 4
                },
                {
                    "level": 3,
                    "exp": 265,
                    "game_id": 3
                },
                {
                    "level": 3,
                    "exp": 283,
                    "game_id": 8
                }
            ],
            "achieve": {
                "like_num": "25",
                "post_num": "0",
                "replypost_num": "28",
                "follow_cnt": "17",
                "followed_cnt": "0",
                "topic_cnt": "0",
                "new_follower_num": "0",
                "good_post_num": "0",
                "follow_collection_cnt": "0",
                "silent_num": "0"
            },
            "community_info": {
                "is_realname": false,
                "agree_status": true,
                "silent_end_time": 0,
                "forbid_end_time": 0,
                "info_upd_time": 1650771774,
                "privacy_invisible": {
                    "post": false,
                    "collect": true,
                    "watermark": false,
                    "reply": true,
                    "post_and_instant": true
                },
                "notify_disable": {
                    "reply": false,
                    "upvote": false,
                    "follow": false,
                    "system": false,
                    "chat": false
                },
                "has_initialized": true,
                "user_func_status": {
                    "enable_history_view": true,
                    "enable_recommend": true,
                    "enable_mention": true,
                    "user_center_view": 1,
                    "show_self_created_villa": "SHOW_SELF_CREATED_VILLA_STATUS_PUBLIC"
                },
                "forum_silent_info": [],
                "last_login_ip": "",
                "last_login_time": 0,
                "created_at": 1623224758
            },
            "avatar_url": "https://bbs-static.miyoushe.com/communityweb/upload/8cbe35bc376ff4cd08dc0a7678492ef2.png",
            "certifications": [],
            "level_exp": null,
            "pendant": "https://bbs-static.miyoushe.com/static/2023/10/23/7717cb46e1b307aa895b7d487d8cd928_147692976671627619.png",
            "is_logoff": false,
            "ip_region": "四川",
            "showText": null,
            "avatar_ext": {
                "avatar_type": 0,
                "avatar_assets_id": "",
                "resources": [],
                "hd_resources": []
            }
        },
        "follow_relation": null,
        "auth_relations": [],
        "is_in_blacklist": false,
        "is_has_collection": false,
        "is_creator": false,
        "customer_service": {
            "is_customer_service_staff": false,
            "game_id": 0
        },
        "audit_info": {
            "is_nickname_in_audit": false,
            "nickname": "",
            "is_introduce_in_audit": false,
            "introduce": "",
            "nickname_status": 0,
            "is_avatar_in_audit": false,
            "avatar_url": "",
            "introduce_status": 0,
            "avatar_status": 0
        },
        "user_silence_status": 0,
        "user_silence_reason": ""
    }
}

**Comment by Theresa-0328** [comment]
无法确定原因，建议自行检查你的网络设置
