### ISSUE TITLE
抢码失败

### ISSUE THREAD

**Issue by chat007h** [Theresa-0328/MHY_Scanner#82]
监听抖音直播间的二维码，直播间一亮码，这个exe软件就关闭了，码也没有抢上

**Comment by Theresa-0328** [comment]
崩溃问题上传生成的dump文件

**Comment by chat007h** [comment]
> 崩溃问题上传生成转储文件

那个是，没看到有啊
![1719469016293](https://github.com/Theresa-0328/MHY_Scanner/assets/153046689/3f0cdf9a-c789-496c-92cc-3db4b085c406)

**Comment by cccwa** [comment]
> 崩溃问题上传生成的dump文件
请问这是什么意思  我是小白看不懂

**Comment by chat007h** [comment]
> > 崩溃问题上传生产dump文件
> > 请问这是什么意思 我是小白看不懂
我也不懂，这是什么文件

**Comment by chat007h** [comment]
> 崩溃问题上传生成转储文件

崩溃后，去找这个文件里面是空的
![Uploading 1719998691789.jpg…]()

**Comment by chat007h** [comment]
> 崩溃问题上传生成的dump文件
崩溃后，去找这个文件里面是空的
![1719998691789](https://github.com/Theresa-0328/MHY_Scanner/assets/153046689/8c1dc188-5174-41f7-a118-a310903d6b0a)
