### ISSUE TITLE
v1.1.8 扫码添加游戏账号问题

### ISSUE THREAD

**Issue by 1-xiaocaikun** [Theresa-0328/MHY_Scanner#86]
使用米游社扫码添加的账号默认登录原神（尽管并无原神账号），以至于崩铁直播间抢码无反应，如图1。
使用崩铁手机客户端扫码无法添加账号，如图3。
希望在添加账号的交互界面可选游戏登录类型（原神、崩铁等）

![IMG_20240706_190322](https://github.com/Theresa-0328/MHY_Scanner/assets/100528119/5970b5a4-51ec-4565-90ca-22e5199d764b)
![U4%AGP6KZ_`7V2F0XHCF%QS](https://github.com/Theresa-0328/MHY_Scanner/assets/100528119/c85b9732-a07d-4342-a105-af0712ea012a)
![){ZJ2URGR P`EZA6_YGR_SS](https://github.com/Theresa-0328/MHY_Scanner/assets/100528119/c4f6b5e8-57b8-498b-a5a6-26b50829aea3)

**Comment by 1-xiaocaikun** [comment]
图2是崩铁官方的二维码支持扫码的app

![U4%AGP6KZ_`7V2F0XHCF%QS](https://github.com/Theresa-0328/MHY_Scanner/assets/100528119/85969819-dfcc-4d66-8e6f-5011c927d135)

**Comment by 1714775263** [comment]
米哈游又改了，等把

**Comment by yb-m** [comment]
狗哈游最近在干嘛，怎么老改啊

**Comment by Theresa-0328** [comment]
扫码登录已失效，没有改动必要了
