### ISSUE TITLE
在1.1.8遇到开始监视屏幕即闪退问题，跪求大佬修复（已试过重新下载，依旧无效)

### ISSUE THREAD

**Issue by user2046** [Theresa-0328/MHY_Scanner#91]
![无标题](https://github.com/user-attachments/assets/f800bc50-6e3b-47b2-8707-86312fb979cc)
以上是Windows事件查看器的截图，希望能帮助到大佬

**Comment by user2046** [comment]
![image](https://github.com/user-attachments/assets/f5c8f80f-01ff-4d64-83d6-60db0661cc80)
不知道为什么用英伟达控制面板指定为核显之后又能正常使用了

**Comment by chat007h** [comment]
我家里电脑可以用，但是公司的电脑用不了

**Comment by Theresa-0328** [comment]
尝试更新nvidia驱动到最新版本，部分nvidia驱动会导致此问题

**Comment by user2046** [comment]
好，谢谢大佬的解答，这里给遇到同样问题的人一个解决方法：指定为使用核显就行
