### ISSUE TITLE
扫码确认后显示二维码已过期

### ISSUE THREAD

**Issue by yukiryo** [Theresa-0328/MHY_Scanner#92]
![image](https://github.com/user-attachments/assets/f3ad3d9d-5ad4-49db-9c46-40737d5e1611)

**Comment by 2016499726** [comment]
我也是这样，账号都添加不上去

**Comment by yb-m** [comment]
老米又改了吧，只能催更作者了

**Comment by CanDuanQi** [comment]
已老实 求放过

**Comment by kongbai312** [comment]
我也这样，上不去
